# Generated by Django 4.1.2 on 2022-12-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogcomment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="Sno",
            new_name="sno",
        ),
        migrations.RemoveField(
            model_name="blogcomment",
            name="parent",
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
